apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: employee-database

spec:
  replicas: 1

  template:
    metadata:
      name: config-server-pod
      labels:
        name: config-server-pod
        app: employee-database

    spec:
      containers:
        - name: config-server
          image: eu.gcr.io/stellar-spark-248921/config-server:1.14
          ports:
            - containerPort: 8888

  selector:
    matchLabels:
      name: config-server-pod
      app: employee-database
