apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    name: config-server
    app: employee-database

spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    name: config-server-pod
    app: employee-database
