apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    name: discovery-service
    app: employee-database

spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    name: discovery-service-pod
    app: employee-database
