server:
  port: 8100
eureka:
  client:
#    fetch-registry: true
    healthcheck:
      enabled: true
    # Docker URL, to connect without just use default http://localhost:8761/eureka/
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

# custom data here
error-message: "Oups! Looks like it's not working."

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
    continue-on-error: false
    schema: classpath:/temp_sql_scripts/schema.sql
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
