server:
  port: 8888
spring:
  application:
    name: "config"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configurations/
eureka:
  client:
    healthcheck:
      enabled: true
    # Docker URL, for running it without just use default localhost
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
