server:
  port: 8200
spring:
  application:
    name: "api-server"
eureka:
  client:
    serviceUrl:
      # it connects to http://localhost:8761/eureka/ by default
      defaultZone: "http://localhost:8761/eureka/"
    healthcheck:
      enabled: true
